version: "{branch}.{build}"

environment:
  matrix:
    - TOXENV: py36-no-ext
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - TOXENV: py37-no-ext
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

    - TOXENV: py38-no-ext
      PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

    # - TOXENV: py39-no-ext
    #   PYTHON: "C:\\Python39-x64\\python"
    #   PYTHONPATH: "C:\\Python39-x64"
    #   PYTHON_VERSION: "3.9.x"
    #   PYTHON_ARCH: "64"

init: SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - pip install tox

build: off

test_script: tox

notifications:
  - provider: Email
    on_build_success: false
    on_build_status_changed: false
