exclude_patterns:
  - "sanic/__main__.py"
  - "sanic/application/logo.py"
  - "sanic/application/motd.py"
  - "sanic/reloader_helpers.py"
  - "sanic/simple.py"
  - "sanic/utils.py"
  - ".github/"
  - "changelogs/"
  - "docker/"
  - "docs/"
  - "examples/"
  - "scripts/"
  - "tests/"
checks:
  argument-count:
    enabled: false
  file-lines:
    config:
      threshold: 1000
  method-count:
    config:
      threshold: 40
  complex-logic:
    enabled: false
  method-complexity:
    config:
      threshold: 10
