exclude_patterns:
  - "sanic/__main__.py"
  - "sanic/reloader_helpers.py"
  - "sanic/simple.py"
  - "sanic/utils.py"
  - ".github/"
  - "changelogs/"
  - "docker/"
  - "docs/"
  - "examples/"
  - "hack/"
  - "scripts/"
