name: 🐞 Bug report
description: Create a report to help us improve
labels: ["bug", "triage"]
body:
  - type: checkboxes
    id: existing
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, make sure to paste any exceptions and tracebacks using markdown code-block syntax to make it easier to read.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code snippet
      description: |
          Relevant source code, make sure to remove what is not necessary. Please try and format your code so that it is easier to read. For example:

              ```python
              from sanic import Sanic

              app = Sanic("Example")
              ```
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: running
    attributes:
      label: How do you run Sanic?
      options:
        - Sanic CLI
        - As a module
        - As a script (`app.run` or `Sanic.serve`)
        - ASGI
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS?
      options:
        - Linux
        - MacOS
        - Windows
        - Other (tell us in the description)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Sanic Version
      description: Check startup logs or try `sanic --version`
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

