blank_issues_enabled: false
contact_links:
  - name: Questions and Help
    url: https://community.sanicframework.org/c/questions-and-help
    about: Do you need help with Sanic? Ask your questions here.
  - name: Discussion and Support
    url: https://discord.gg/FARQzAEMAA
    about: For live discussion and support, checkout the Sanic Discord server.
