name: Run security tests

on:
  pull_request:
    branches:
      - main
      - current-release
      - "*LTS"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run_format_tests:
    name: "Security - Python ${{ matrix.config.python-version }}"
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { python-version: "3.8", tox-env: security }
          - { python-version: "3.9", tox-env: security }
          - { python-version: "3.10", tox-env: security }
          - { python-version: "3.11", tox-env: security }
    steps:
      - name: Run format tests
        uses: prryplatypus/simple-tox@main
        with:
          python-version: ${{ matrix.config.python-version }}
          tox-env: ${{ matrix.config.tox-env }}
