name: Run Unit Tests (Linux)

on:
  pull_request:
    branches:
      - main
      - current-release
      - "*LTS"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run_unit_tests:
    name: Run Unit Tests on Python ${{ matrix.config.python-version }}
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: true
      matrix:
        config:
          - { python-version: "3.7", tox-env: py37 }
          - { python-version: "3.7", tox-env: py37-no-ext }
          - { python-version: "3.8", tox-env: py38 }
          - { python-version: "3.8", tox-env: py38-no-ext }
          - { python-version: "3.9", tox-env: py39 }
          - { python-version: "3.9", tox-env: py39-no-ext }
          - { python-version: "3.10", tox-env: py310 }
          - { python-version: "3.10", tox-env: py310-no-ext }
          - { python-version: "3.11", tox-env: py311 }
          - { python-version: "3.11", tox-env: py311-no-ext }

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.config.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run unit tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: tox -e ${{ matrix.config.tox-env }}
